---

# Install Redis
- yum: name=redis state=present
- name: ensure redis is running
  service: name=redis state=started enabled=yes
  notify:
    - restart redis

# Install php-redis
- yum: name=php-redis state=present
  notify:
    - restart httpd