---

- fail: msg="if user_name is not defined"
  when: "user_name is not defined"

- fail: msg="if user_password is not defined"
  when: "user_password is not defined"

- user: name={{ user_name }} password={{ user_password }}
- name: insert id_rsa.pub to authorized_keys
  authorized_key: user={{ user_name }} key="{{ item }}"
  with_file: user_auth_keys
- template: src=sudoers.d/user dest=/etc/sudoers.d/{{ user_name }} owner=root group=root mode=440
  when: "user_can_sudo"
