---
- fail: msg="if vhost_host_name is undefined"
  when: "vhost_host_name is undefined"

- name: create ssl cert store directory
  file: dest={{ vhost_ssl_cert_dir }} state=directory

- name: copy ssl certificate
  copy: src={{ vhost_ssl_cert }} dest={{ vhost_ssl_cert_dir }}/{{ vhost_host_name }}.cer owner=root group=root mode=644
  when: "vhost_ssl_cert is defined"

- name: copy ssl private key
  copy: src={{ vhost_ssl_key }} dest={{ vhost_ssl_cert_dir }}/{{ vhost_host_name }}.key owner=root group=root mode=600
  when: "vhost_ssl_key is defined"

- name: copy ssl intermediate certificate
  copy: src={{ vhost_ssl_ca_cert }} dest={{ vhost_ssl_cert_dir }}/{{ vhost_host_name }}.cacert.cer owner=root group=root mode=644
  when: "vhost_ssl_ca_cert is defined"

- name: create virtual host documents directory
  file: dest=/var/www/html/{{ vhost_host_name }} state=directory

- name: create virtual host httpd conf
  template: src=vhost.conf dest=/etc/httpd/conf.d/{{ vhost_host_name }}.conf owner=root group=root mode=644
  notify:
    - restart httpd
