---
- name: validate iptables_accept_ports contains only numbers
  assert: that="item|int > 0"
  with_items: iptables_accept_ports

- yum: name=iptables state=present
- name: copy iptables config
  template: src=iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600 backup=yes
  notify:
    - restart iptables
- name: ensure iptables is running
  service: name=iptables state=started enabled=yes
