---

- yum: name={{ item }} state=present
  with_items:
    - libcurl-devel
    - ruby-devel
    - @development

- gem: name=fluent-plugin-elasticsearch state=present user_install=no executable=/usr/lib64/fluent/ruby/bin/fluent-gem