---

# Install elasticsearch
# http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-repositories.html
- rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
- template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644 backup=yes

- yum: name=java-1.7.0-openjdk state=present
- yum: name=elasticsearch state=present

- name: ensure elasticsearch is running
  service: name=elasticsearch state=started enabled=yes

- name: install kibana plugin
  command: /usr/share/elasticsearch/bin/plugin -i elasticsearch/kibana creates=/usr/share/elasticsearch/plugins/kibana


- name: check if td-agent is installed
  command: rpm -q td-agent
  register: tdagent_installed

- include: fluent-plugin-elasticsearch.yml
  when: tdagent_installed.rc == 0
