---

- fail: msg="if mysql_root_password is not defined"
  when: "mysql_root_password is not defined"

# Install MySQL Server
- yum: name=mysql-server state=present
- yum: name=phpMyAdmin state=present
- yum: name=MySQL-python state=present

- name: copy mysql config
  template: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=644 backup=yes
  notify:
    - restart mysqld

- name: ensure mysqld is running
  service: name=mysqld state=started enabled=yes

# set root password
- mysql_user: name=root host=localhost password=$mysql_root_password
- template: src=my_credentials.cnf dest=/root/.my.cnf owner=root mode=600

- name: create default db
  mysql_db: name=dev collation=utf8_unicode_ci encoding=utf8